context.modules = [
  { name = libpipewire-module-loopback
    args = {
      node.description = "Elgato Wave:3 VST2 Capture"
      capture.props  = {
        node.name = "elgato_wave3_vst2_capture"
        target.object = "Carla"
        node.passive = true
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name = "elgato_wave3_vst2"
        node.description = "Elgato Wave:3 VST2"
        media.class = Audio/Source
        audio.position = [ FL FR ]
      }
    }
  }
]
